name: Build, Push, and Deploy

on:
  workflow_dispatch:
    inputs:
      bucket-subfolder-suffix:
        description: "Bucket subfolder name suffix (optional)"
        required: false
        default: ""
        type: string
  push:
    branches:
      - "develop"
      - 'main'
    tags:
      - "v*"

jobs:
  build:
    name: Build Container Image
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.deploy-tag.outputs.image_tag }}
      image_name: ${{ steps.deploy-tag.outputs.image_name }}
      environment_name: ${{ steps.deploy-info.outputs.environment_name }}
      bucketname: ${{ steps.deploy-tag.outputs.bucket_name }}
      bucketfolder: ${{ steps.deploy-tag.outputs.bucket_subfolder}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Parse deployment info
        id: deploy-info
        run: |
          # Determine environment to deploy to
          if ${{ github.ref_type == 'tag'}}; then
            environment_name="prod"
            credentials_json='${{ secrets.PIPELINE_EPO_PROD_PROJECT }}'
          elif ${{ contains(github.ref_name, 'main') || contains(github.base_ref, 'main') }}; then
            environment_name="int"
            credentials_json='${{ secrets.SKYVIEWER_INT_SERVICE_ACCOUNT }}'
          else
            environment_name="dev"
            credentials_json='${{ secrets.DEV_SA_KEY }}'
          fi
          deploymentname="investigations-client"
          echo deploymentname=$deploymentname >> "$GITHUB_OUTPUT"
          echo environment_name=$environment_name >> "$GITHUB_OUTPUT"
          echo credentials_json=$credentials_json >> "$GITHUB_OUTPUT"
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: |
            gcr.io/skyviewer/investigations-client-k8s,enable=${{ steps.deploy-info.outputs.environment_name == 'dev' }}
            gcr.io/edc-int-6c5e/investigations-client-k8s,enable=${{ steps.deploy-info.outputs.environment_name == 'int' }}
            gcr.io/edc-prod-eef0/investigations-client-k8s,enable=${{ steps.deploy-info.outputs.environment_name == 'prod' }}
          flavor: |
            latest=${{ github.event_name == 'push'}}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      - name: Parse deploy tag
        id: deploy-tag
        run: |
          # Parse container image tag to deploy
          full_tag=$(echo "$DOCKER_METADATA_OUTPUT_JSON" | jq -r '.tags[] | limit(1; select(. | test(":sha-|:v.")))')
          echo "Will use tag \"$full_tag\" for deployment."
          echo image_tag=$(echo "$full_tag" | cut -f2 -d:) >> "$GITHUB_OUTPUT"
          echo image_name=$(echo "$full_tag" | cut -f1 -d:) >> "$GITHUB_OUTPUT"
          echo full_tag=$full_tag >> "$GITHUB_OUTPUT"
          bucket_name=investigations-${{ steps.deploy-info.outputs.environment_name }}
          bucket_subfolder=$(echo "$full_tag" | cut -f2 -d:)-${{ steps.deploy-info.outputs.date }}
          echo bucket_name=investigations-${{ steps.deploy-info.outputs.environment_name }} >> "$GITHUB_OUTPUT"
          echo bucket_subfolder=$(echo "$full_tag" | cut -f2 -d:)-${{ steps.deploy-info.outputs.date }} >> "$GITHUB_OUTPUT"
          echo "bucket_name: $bucket_name"
          echo "bucket_subfolder: $bucket_subfolder"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GCP
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: ${{ steps.deploy-info.outputs.credentials_json }}
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"
      - run: gcloud --quiet auth configure-docker

      - name: Fetch and Set Environment Variables from Secret Manager
        id: deploy-secrets
        run: |
          # Get appropriate secret name
          SECRET_NAME=$(gcloud secrets list --filter="labels.deployment:${{ steps.deploy-info.outputs.deploymentname }}" --format="value(name)")
          # The secret value must be a single-line JSON string.
          SECRET_JSON=$(gcloud secrets versions access latest --secret=$SECRET_NAME)

          # check secrets are being read
          echo "$SECRET_JSON" | jq 'keys | length'

          # Write secrets and format to .env file which will be mounted into docker build step
          echo "$SECRET_JSON " | jq -r 'to_entries[] | "\(.key)=\(.value)"' > .env
  
      - name: Build and push
        uses: docker/build-push-action@v6.8.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-to: |
            type=gha
          cache-from: |
            type=gha
          build-args: |
            BASE_TAG=k8s
            RUN_BUILD=false
      - name: Run static build in docker container based on .env file
        uses: docker/build-push-action@v6.19.2
        with:
          context: .
          push: false
          target: nextjs-copy
          outputs: type=local,dest=./.next
          build-args: |
            RUN_BUILD=false
          cache-from: |
            type=gha

      - name: Upload to GCS bucket
        uses: google-github-actions/upload-cloud-storage@v3
        with:
          path: '.next'
          destination: '${{ steps.deploy-tag.outputs.bucket_name}}/${{ steps.deploy-tag.outputs.bucket_subfolder}}${{ github.event.inputs.bucket-subfolder-suffix }}'
          gzip: false
      
      - name: Add lifecycle Policies
        env:
          BUCKET_FOLDER_PREFIX: ${{ steps.deploy-tag.outputs.bucket_subfolder }}${{ github.event.inputs.bucket-subfolder-suffix }}
          BUCKET_NAME: ${{ steps.deploy-tag.outputs.bucket_name }}
        run: |
          cat > lifecycle.json <<EOF
          {
            "lifecycle": {
               "rule": [
                {
                  "action": {
                    "type": "Delete"
                  },
                  "condition": {
                    "age": 1,
                    "matchesPrefix": [
                      "$BUCKET_FOLDER_PREFIX/.next/cache/fetch-cache/",
                      "$BUCKET_FOLDER_PREFIX/.next/cache/images/"
                    ]
                  }
                }
              ]
            }
          }
          EOF
          gcloud storage buckets update gs://$BUCKET_NAME --lifecycle-file=lifecycle.json
          rm lifecycle.json

      - name: Summary
        run: |
          cat <<-EOT >> "$GITHUB_STEP_SUMMARY"
            # Container Build Completed

            ## Tags
            ${{ steps.meta.outputs.tags }}
          EOT

  deploy:
    name: Trigger deploy to ${{ needs.build.outputs.environment_name }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Generate Webhook Payload
        id: payload
        run: |-
          PARAMETERS=(
            client.image.tag=${{ needs.build.outputs.image_tag }}
            client.image.repository=${{ needs.build.outputs.image_name }}
            global.gcsFuse.bucketName=${{ needs.build.outputs.bucketname }}
            global.gcsFuse.bucketFolder=${{ needs.build.outputs.bucketfolder }}${{ github.event.inputs.bucket-subfolder-suffix }}/.next
          )
          DATA="{
            \"app_name\": \"investigations\",
            \"environment_name\": \"${{ needs.build.outputs.environment_name }}\",
            \"parameters\": $(jq -c -n '$ARGS.positional' --args ${PARAMETERS[@]}),
            \"date\": \"\"
          }"
          echo "data=$(echo $DATA | jq -rc '.')" >> "$GITHUB_OUTPUT"
      - uses: lasith-kg/dispatch-workflow@v1.7.0
        id: dispatch
        name: Trigger Deployment
        with:
          dispatch-method: repository_dispatch
          repo: edc-deploy
          owner: lsst-epo
          event-type: app_update_values
          token: ${{ secrets.EDC_DEPLOY_GITHUB_TOKEN_FOR_REST_API }}
          workflow-inputs: ${{ steps.payload.outputs.data }}
          discover: true
      - name: Await Run ID ${{ steps.dispatch.outputs.run-id }}
        uses: Codex-/await-remote-run@v1.10.0
        with:
          token: ${{ secrets.EDC_DEPLOY_GITHUB_TOKEN_FOR_REST_API }}
          repo: edc-deploy
          owner: lsst-epo
          run_id: ${{ steps.dispatch.outputs.run-id }}
          run_timeout_seconds: 1500
